# Generated by Django 3.2.6 on 2021-08-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='email',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
