# Generated by Django 3.2.6 on 2021-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
