# Generated by Django 3.2.6 on 2021-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
